# Generated by Django 5.1.4 on 2024-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddataset",
            name="columns",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadeddataset",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
