# Generated by Django 5.1.4 on 2024-12-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_app", "0002_uploadeddataset_columns_alter_uploadeddataset_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadeddataset",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="uploadeddataset",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
