# Generated by Django 5.1.4 on 2024-12-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_app", "0003_alter_uploadeddataset_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="algorithm",
            field=models.CharField(default="auto", max_length=50),
        ),
    ]
