# Generated by Django 5.1.4 on 2024-12-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ml_app", "0004_analysisresult_algorithm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisresult",
            name="algorithm",
        ),
    ]
